# Generated by Django 2.0.1 on 2018-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_goods', '0003_auto_20180202_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodinfo',
            name='gunit',
            field=models.CharField(default='500g', max_length=20),
        ),
    ]
